LIBDIRS= -framework GLUT -framework OpenGL
LDLIBS = -lobjc -lm

CPPFLAGS= -Wno-deprecated
LDFLAGS= $(LIBDIRS)

TARGETS = simple double

SRCS = simple.cpp double.cpp

OBJS =  $(SRCS:.cpp=.o)

CXX = g++

default: $(TARGETS)
